import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.FileWriter;
import java.io.PrintWriter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class POS extends javax.swing.JFrame {
    
    private int itemIdCounter = 1; // Add this variable to keep track of item IDs

    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
        scaleButtonIcon(jbtnOrangeJuice, "src/Images/orange-juice.jpg");
        scaleButtonIcon(jbtn7up, "src/Images/7up.jpg");
        scaleButtonIcon(jbtnChickenNoodles, "src/Images/chickennoodles.jpg");
        scaleButtonIcon(jbtnChickenBurger, "src/Images/chickenburger.jpg");
        scaleButtonIcon(jbtnVegetarianPizza, "src/Images/vegetarianpizza.jpg");
        scaleButtonIcon(jbtnCoke, "src/Images/coke.jpg");
        scaleButtonIcon(jbtnFruitsCake, "src/Images/fruitscake.jpg");
        scaleButtonIcon(jbtnChocolateCake, "src/Images/chocolatecake.jpg");
        scaleButtonIcon(jbtnStawberryCake, "src/Images/strawberrycake.jpg");
        scaleButtonIcon(jbtnMineral, "src/Images/mineralswater.png");
        scaleButtonIcon(jbtnGreenTea, "src/Images/greentea.jpg");
        scaleButtonIcon(jbtnChocolateCoffee, "src/Images/chocolatecoffee.jpg");
        scaleButtonIcon(jbtnCappucino, "src/Images/cappuccinocoffee.jpg");
        scaleButtonIcon(jbtnColdCoffee, "src/Images/coldcoffee.jpg");
        
        // Update time and date labels 
        updateTimeLabel();
        updateDateLabel();

        // Set up a timer to update time every second
        javax.swing.Timer timer = new javax.swing.Timer(1000, (e) -> {
            updateTimeLabel();
        });
        timer.start();
    }
    
    private void scaleButtonIcon(javax.swing.JButton button, String imagePath) {
        // Load the original icon
        ImageIcon originalIcon = new ImageIcon(imagePath);

        // Get the button size
        int buttonWidth = button.getWidth();
        int buttonHeight = button.getHeight();

        // Scale the icon to fit the button
        Image scaledImage = originalIcon.getImage().getScaledInstance(buttonWidth, buttonHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Set the scaled icon as the button's icon
        button.setIcon(scaledIcon);
    }
    
    private void updateTimeLabel() {
        // Get current time
        Calendar calendar = Calendar.getInstance();
        Date now = calendar.getTime();

        // Format time in 12-hour format with AM/PM indicator
        SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
        String formattedTime = timeFormat.format(now);

        // Update time label
        timeLabel.setText(formattedTime);
    }
    
    private void updateDateLabel() {
        // Get current date
        Calendar calendar = Calendar.getInstance();
        Date now = calendar.getTime();

        // Format date as "Day, DD-MM-YYYY"
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, dd-MM-yyyy");
        String formattedDate = dateFormat.format(now);

        // Update date label
        dateLabel.setText(formattedDate);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtPayMethod = new javax.swing.JComboBox<>();
        jtxtChange = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnCappucino = new javax.swing.JButton();
        jbtnFruitsCake = new javax.swing.JButton();
        jbtnChickenBurger = new javax.swing.JButton();
        jbtnRawCoffee = new javax.swing.JButton();
        jbtnStawberryCake = new javax.swing.JButton();
        jbtnVegetarianPizza = new javax.swing.JButton();
        jbtnOrangeJuice = new javax.swing.JButton();
        jbtnChickenNoodles = new javax.swing.JButton();
        jbtnCoke = new javax.swing.JButton();
        jbtnMineral = new javax.swing.JButton();
        jbtnRainbowCake = new javax.swing.JButton();
        jbtnGreenTea = new javax.swing.JButton();
        jbtnChocolateCoffee = new javax.swing.JButton();
        jbtnChocolateCake = new javax.swing.JButton();
        jbtnColdCoffee = new javax.swing.JButton();
        jbtnHomemadeCake = new javax.swing.JButton();
        jbtnMatchaCoffee = new javax.swing.JButton();
        jbtn7up = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtTotal1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPrint = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(209, 203, 179));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 50));

        jtxtPayMethod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtPayMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel7.add(jtxtPayMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 200, 50));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Change");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Payment Method");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Cash");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 450, 190));

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setBackground(new java.awt.Color(65, 64, 231));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 160, 50));

        jbtnPay.setBackground(new java.awt.Color(16, 180, 16));
        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 50));

        jButton21.setBackground(new java.awt.Color(226, 62, 101));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton21.setText("Exit");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 50));

        jbtnPrint.setBackground(new java.awt.Color(19, 186, 228));
        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 50));

        jbtnRemove.setBackground(new java.awt.Color(204, 0, 0));
        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 390, 190));

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel9.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 50));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel9.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Total");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("SubTotal");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Tax");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel9.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 200, 50));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 1340, 210));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCappucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cappuccinocoffee.jpg"))); // NOI18N
        jbtnCappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCappucinoActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 120, 130));

        jbtnFruitsCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fruitscake.jpg"))); // NOI18N
        jbtnFruitsCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFruitsCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnFruitsCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, 130));

        jbtnChickenBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chickenburger.jpg"))); // NOI18N
        jbtnChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenBurgerActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 130));

        jbtnRawCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RawCoffee.png"))); // NOI18N
        jbtnRawCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRawCoffeeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnRawCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 120, 130));

        jbtnStawberryCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/strawberrycake.jpg"))); // NOI18N
        jbtnStawberryCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStawberryCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnStawberryCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 120, 130));

        jbtnVegetarianPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vegetarianpizza.jpg"))); // NOI18N
        jbtnVegetarianPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVegetarianPizzaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnVegetarianPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 120, 130));

        jbtnOrangeJuice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orange-juice.jpg"))); // NOI18N
        jbtnOrangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrangeJuiceActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnOrangeJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 130));

        jbtnChickenNoodles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chickennoodles.jpg"))); // NOI18N
        jbtnChickenNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenNoodlesActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenNoodles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 130));

        jbtnCoke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coke.jpg"))); // NOI18N
        jbtnCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCokeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 130));

        jbtnMineral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mineralswater.png"))); // NOI18N
        jbtnMineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMineralActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnMineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 120, 130));

        jbtnRainbowCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rainbow.jpg"))); // NOI18N
        jbtnRainbowCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRainbowCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnRainbowCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 130));

        jbtnGreenTea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/greentea.jpg"))); // NOI18N
        jbtnGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGreenTeaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnGreenTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 120, 130));

        jbtnChocolateCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chocolatecoffee.jpg"))); // NOI18N
        jbtnChocolateCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChocolateCoffeeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChocolateCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 130));

        jbtnChocolateCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chocolatecake.jpg"))); // NOI18N
        jbtnChocolateCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChocolateCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChocolateCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 120, 130));

        jbtnColdCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coldcoffee.jpg"))); // NOI18N
        jbtnColdCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnColdCoffeeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnColdCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 120, 130));

        jbtnHomemadeCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Homemadecake.png"))); // NOI18N
        jbtnHomemadeCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomemadeCakeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHomemadeCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 120, 130));

        jbtnMatchaCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/matcha-cofee.png"))); // NOI18N
        jbtnMatchaCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMatchaCoffeeActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnMatchaCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 120, 130));

        jbtn7up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7up.jpg"))); // NOI18N
        jbtn7up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7upActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn7up, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 790, 470));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Item", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 320, 380));

        jtxtTotal1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jtxtTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotal1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 320, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee-lab-high-resolution-logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 190, 180));

        dateLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        dateLabel.setText("Date");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 150, -1));

        timeLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        timeLabel.setText("Time");
        getContentPane().add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 150, -1));

        jTextAreaPrint.setColumns(20);
        jTextAreaPrint.setRows(5);
        jTextAreaPrint.setToolTipText("");
        jScrollPane2.setViewportView(jTextAreaPrint);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 200, 320, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    public void ItemCost()
    {
        //int sum = 0;
        double sum = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            //sum = sum + Integer.parseInt(jTable1.getValueAt(i, 2).toString());
            sum =  sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
          
        }
        //jtxtSubTotal.setText(Integer.toString(sum));
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 *0.10)/100;
        String iTaxTotal = String.format("₱ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("₱ %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("₱ %.2f", cTax + cTotal1);
        jtxtTotal.setText(iTotal); 
        
        String iPrint = String.format("Total is: ₱ %.2f", cTax + cTotal1);
        jtxtTotal1.setText(iPrint);
       
    }

     public void Change()
    {        
        double sum = 0;
        double tax =3.9;        
        double cash = Double.parseDouble(jtxtDisplay.getText());
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum =  sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());            
        }
        double cTax = (sum * tax)/100;
        double cChange = (cash - (sum + cTax));      
        String ChangeGiven = String.format("₱ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);     
  
}
    
private JFrame frame;
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Point of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        // Validate input for jtxtDisplay
        String input = jtxtDisplay.getText().replaceAll("[^\\d.]", ""); // Remove non-digit characters
        if (!input.matches("\\d*\\.?\\d+")) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if cash is greater than or equal to the total
        double cash = Double.parseDouble(input);

        // Extract the numeric part from jtxtTotal (remove currency symbol and whitespace)
        String totalText = jtxtTotal.getText().replaceAll("[^\\d.]", "");
        double total = Double.parseDouble(totalText);

        if (cash < total) {
            JOptionPane.showMessageDialog(this, "Insufficient cash. Please enter an amount equal to or greater than the total.", "Payment Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Proceed with payment
        if (jtxtPayMethod.getSelectedItem().equals("Cash")) {
            Change();
        } else {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        RecordTable.setRowCount(0);
         jtxtChange.setText("");
                jtxtDisplay.setText("");
                jtxtTax.setText("");
                jtxtSubTotal.setText("");
                jtxtTotal.setText("");
                jtxtTotal1.setText("");
                itemIdCounter = 1;
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnOrangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrangeJuiceActionPerformed
        double PriceOfItem = 50.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Orange Juice", "1", PriceOfItem});
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnOrangeJuiceActionPerformed

    private void jbtn7upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7upActionPerformed
        double PriceOfItem = 30.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "7up","1",PriceOfItem});
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtn7upActionPerformed

    private void jbtnChickenNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenNoodlesActionPerformed
        double PriceOfItem = 140.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Chicken Noodles","1",PriceOfItem});
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnChickenNoodlesActionPerformed

    private void jbtnChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenBurgerActionPerformed
       double PriceOfItem = 90.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Chicken Burger","1",PriceOfItem});
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnChickenBurgerActionPerformed

    private void jbtnVegetarianPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVegetarianPizzaActionPerformed
        double PriceOfItem = 150.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Vegetarian Pizza","1",PriceOfItem});        
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnVegetarianPizzaActionPerformed

    private void jbtnCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCokeActionPerformed
        double PriceOfItem = 40.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Coke","1",PriceOfItem});        
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnCokeActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();          
             
        int  RemoveItem =  jTable1.getSelectedRow();                      
        if (RemoveItem >= 0)
        {
        model.removeRow(RemoveItem);  
        }   
        
        ItemCost();
        
        if (jtxtPayMethod.getSelectedItem().equals("Cash"))
            {
                Change();               
            }
        
        String Enternumber = jtxtDisplay.getText();
                       
        if (Enternumber == "" && jtxtPayMethod.getSelectedItem().equals("Cash"))
        {      
            
                jtxtChange.setText("");
                jtxtDisplay.setText("");
            }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnRainbowCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRainbowCakeActionPerformed
        double PriceOfItem = 100.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Rainbow Cake","1",PriceOfItem});        
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnRainbowCakeActionPerformed

    private void jbtnFruitsCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFruitsCakeActionPerformed
      double PriceOfItem = 120.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Fruits Cake","1",PriceOfItem});       
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnFruitsCakeActionPerformed

    private void jbtnChocolateCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChocolateCakeActionPerformed
        double PriceOfItem = 120.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Chocolate Cake","1",PriceOfItem});      
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnChocolateCakeActionPerformed

    private void jbtnStawberryCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStawberryCakeActionPerformed
         double PriceOfItem = 120.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Stawberry Cake","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnStawberryCakeActionPerformed

    private void jbtnMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMineralActionPerformed
       double PriceOfItem = 20.00;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Mineral Water","1",PriceOfItem});  
        itemIdCounter++; // Increment the item ID counter
        ItemCost(); 
    }//GEN-LAST:event_jbtnMineralActionPerformed

    private void jbtnGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGreenTeaActionPerformed
        double PriceOfItem = 50.00;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Green Tea","1",PriceOfItem});      
        itemIdCounter++; // Increment the item ID counter
        ItemCost(); 
    }//GEN-LAST:event_jbtnGreenTeaActionPerformed

    private void jbtnChocolateCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChocolateCoffeeActionPerformed
        double PriceOfItem = 60.00;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Chocolate Coffee","1",PriceOfItem});       
        itemIdCounter++; // Increment the item ID counter
        ItemCost(); 
    }//GEN-LAST:event_jbtnChocolateCoffeeActionPerformed

    private void jbtnCappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCappucinoActionPerformed
         double PriceOfItem = 80.00;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Cappucino Coffee","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnCappucinoActionPerformed

    private void jbtnColdCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnColdCoffeeActionPerformed
        double PriceOfItem = 60.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Cold Coffee","1",PriceOfItem});     
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnColdCoffeeActionPerformed

    private void jbtnHomemadeCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomemadeCakeActionPerformed
        double PriceOfItem = 100.0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Homemade Cake","1",PriceOfItem});        
        ItemCost();
    }//GEN-LAST:event_jbtnHomemadeCakeActionPerformed

    private void jbtnMatchaCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMatchaCoffeeActionPerformed
        double PriceOfItem = 80.00;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Matcha Coffee","1",PriceOfItem});      
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnMatchaCoffeeActionPerformed

    private void jbtnRawCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRawCoffeeActionPerformed
        double PriceOfItem = 110.00;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{itemIdCounter, "Raw Coffee","1",PriceOfItem});        
        itemIdCounter++; // Increment the item ID counter
        ItemCost();
    }//GEN-LAST:event_jbtnRawCoffeeActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");

        // Clear previous text
        jTextAreaPrint.setText("");

        // Add header
        String headerRow = String.format("%-4s %-30s %-10s %s\n", "Id", "Item", "Quantity", "Price");
        jTextAreaPrint.append("                        Coffee Lab\n" +
                             "-------------------------------------------------------------------\n" +
                             headerRow +
                             "-------------------------------------------------------------------\n");

        // Add items from jTable1
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String id = model.getValueAt(i, 0).toString();
            String item = model.getValueAt(i, 1).toString();
            String quantity = model.getValueAt(i, 2).toString();
            String price = model.getValueAt(i, 3).toString();

            // Adjust the number of spaces based on your desired column width
            String row = String.format("%-4s %-30s %-10s %s\n", id, item, quantity, price);
            jTextAreaPrint.append(row);
        }

        // Add Sub Total, Cash, Balance, and footer
        String subTotal = String.format("\nSub Total: %-10s\n", jtxtSubTotal.getText());
        String cash = String.format("Cash: %-10s\n", jtxtDisplay.getText());
        String balance = String.format("Balance: %-10s\n", jtxtChange.getText());

        jTextAreaPrint.append("-------------------------------------------------------------------\n");
        jTextAreaPrint.append(subTotal);
        jTextAreaPrint.append(cash);
        jTextAreaPrint.append(balance);
        jTextAreaPrint.append("\n                    Thanks For Your Business...!\n");
        jTextAreaPrint.append("-------------------------------------------------------------------\n");

        try {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jtxtTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotal1ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaPrint;
    private javax.swing.JButton jbtn7up;
    private javax.swing.JButton jbtnCappucino;
    private javax.swing.JButton jbtnChickenBurger;
    private javax.swing.JButton jbtnChickenNoodles;
    private javax.swing.JButton jbtnChocolateCake;
    private javax.swing.JButton jbtnChocolateCoffee;
    private javax.swing.JButton jbtnCoke;
    private javax.swing.JButton jbtnColdCoffee;
    private javax.swing.JButton jbtnFruitsCake;
    private javax.swing.JButton jbtnGreenTea;
    private javax.swing.JButton jbtnHomemadeCake;
    private javax.swing.JButton jbtnMatchaCoffee;
    private javax.swing.JButton jbtnMineral;
    private javax.swing.JButton jbtnOrangeJuice;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRainbowCake;
    private javax.swing.JButton jbtnRawCoffee;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnStawberryCake;
    private javax.swing.JButton jbtnVegetarianPizza;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JComboBox<String> jtxtPayMethod;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtTotal1;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
